### ISSUE TITLE
Investigate Web3 1.0

### ISSUE THREAD

**Issue by prettymuchbryce** [dydxprotocol/dydx.js#78]
We should investigate the feasibility of switching to Web3 1.0. There may have been stability improvements in the newer versions, but in the past we have avoided switching because the story around the compatibility with MetaMask was unclear.

Lets invest some cycles and do some real investigation around whether or not we can transition to Web3 1.0

https://github.com/MetaMask/metamask-extension/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+web3+1.0

https://guillaumeduveau.com/en/blockchain/ethereum/metamask-web3

https://github.com/MetaMask/metamask-extension/issues/3642#issuecomment-422217443

**Comment by elie222** [comment]
Ya... Incredible how long it's taking for them to make the upgrade to support 1.0
