### ISSUE TITLE
Support both promise, and non-promise transaction approach [2]

### ISSUE THREAD

**Issue by prettymuchbryce** [dydxprotocol/dydx.js#97]
Support both promise and non-promise approaches for sending transactions.

Sometimes it's useful for the promise to resolve only when the transaction is mined, but other times it is useful to get access to the transaction hash before the transaction has been mined.

We should support both for all external-facing methods that make contract calls.

**Comment by AntonioJuliano** [comment]
Part of https://github.com/dydxprotocol/issues/issues/81
